sudo: false
language: python
python:
- "3.5"
before_install:
- sudo apt-get update
- sudo apt-get install -y libgdal-dev
install:
- pip install -r requirements.txt
cache: pip
services:
- postgresql
env:
- DJANGO_SETTINGS_MODULE="vet_project.settings_travis"
script:
- python manage.py test
