# Generated by Django 2.0 on 2018-01-14 18:33

from django.db import migrations, models
import vet_app.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('vet', 'Docteur Vétérinaire'), ('asv', 'ASV')], max_length=100, verbose_name='role')),
                ('first_name', models.CharField(max_length=200, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=200, verbose_name='Nom de famille')),
                ('image', vet_app.fields.ContentTypeRestrictedFileField(blank=True, help_text='Uploader une image au format JPG, (!) taille maximale du fichier: 2Mio', null=True, upload_to='%Y/%m/%d/%H/%M/%S', verbose_name='image de profile')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création de la rubrique')),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': "L'equipe",
            },
        ),
    ]
