# Generated by Django 2.0 on 2018-01-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='role',
            field=models.CharField(choices=[('Docteur Vétérinaire', 'Docteur Vétérinaire'), ('ASV', 'ASV'), ('Secrétaire comptable', 'Secrétaire comptable')], max_length=100, verbose_name='role'),
        ),
    ]
