# Generated by Django 2.0 on 2018-01-15 17:44

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vet_app', '0004_auto_20180115_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='cropping_image',
            field=image_cropping.fields.ImageRatioField('image', '360x360', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping image'),
        ),
        migrations.AlterField(
            model_name='people',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, help_text='Uploader une image au format', null=True, upload_to='people_profile_image', verbose_name='image de profile'),
        ),
    ]
