# Generated by Django 2.0 on 2018-01-15 18:03

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vet_app', '0005_auto_20180115_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='cropping_image',
            field=image_cropping.fields.ImageRatioField('image', '360x360', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text="Choisissez la partie de l'image à afficher", hide_image_field=False, size_warning=False, verbose_name="Selection dans l'image de profil"),
        ),
        migrations.AlterField(
            model_name='people',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, help_text='Uploader une image de profile pour la personne', null=True, upload_to='people_profile_image', verbose_name='Image de profile'),
        ),
        migrations.AlterField(
            model_name='people',
            name='role',
            field=models.CharField(choices=[('Docteur Vétérinaire', 'Docteur Vétérinaire'), ('ASV', 'ASV'), ('Secrétaire comptable', 'Secrétaire comptable'), ('Stagiaire', 'Stagiaire')], max_length=100, verbose_name='role'),
        ),
    ]
