# Generated by Django 2.0 on 2018-01-16 05:57

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vet_app', '0006_auto_20180115_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Personne', 'verbose_name_plural': "L'équipe"},
        ),
        migrations.AlterField(
            model_name='people',
            name='cropping_image',
            field=image_cropping.fields.ImageRatioField('image', '360x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text="Choisissez la partie de l'image à afficher", hide_image_field=False, size_warning=False, verbose_name="Selection dans l'image de profil"),
        ),
    ]
