# Generated by Django 2.0 on 2018-01-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_app', '0007_auto_20180116_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='people',
            name='last_name',
        ),
        migrations.AddField(
            model_name='people',
            name='name',
            field=models.CharField(default='TBD', help_text="Nom tel qu'il apparaîtra sur la page equipe", max_length=200, verbose_name='Prénom, Nom de famille'),
            preserve_default=False,
        ),
    ]
