# Generated by Django 2.0 on 2018-01-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_app', '0008_auto_20180116_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='role',
        ),
        migrations.AddField(
            model_name='people',
            name='role_int',
            field=models.IntegerField(choices=[(0, 'Docteur Vétérinaire Associé(e)'), (1, 'Docteur Vétérinaire'), (2, 'ASV'), (3, 'Secrétaire comptable'), (4, 'Stagiaire')], default=1, verbose_name='role'),
            preserve_default=False,
        ),
    ]
