# Generated by Django 2.0 on 2018-01-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_app', '0009_auto_20180116_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titre tel qu'il apparaîtra sur le menu de gauche", max_length=200, verbose_name='Titre')),
                ('category_int', models.IntegerField(choices=[(0, 'Animaux de compagnie'), (1, 'Rurale'), (2, 'Equine')], verbose_name='categorie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création de la rubrique')),
            ],
            options={
                'verbose_name': 'Fiche service',
                'verbose_name_plural': 'Fiches service',
            },
        ),
    ]
