# Generated by Django 2.0 on 2018-01-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_app', '0010_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ('order',), 'verbose_name': 'Personne', 'verbose_name_plural': "L'équipe"},
        ),
        migrations.AddField(
            model_name='people',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
