# Generated by Django 2.0 on 2018-01-17 18:55

from django.db import migrations


def set_people_order(apps, schema_editor):
    People = apps.get_model('vet_app', 'People')

    for idx, person in enumerate(People.objects.order_by('role_int', 'name')):
        person.order = idx
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vet_app', '0011_auto_20180117_1817'),
    ]

    operations = [
        migrations.RunPython(set_people_order),
    ]
