# Generated by Django 2.0 on 2018-01-18 06:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet_app', '0012_auto_20180117_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
