# Generated by Django 2.0 on 2018-01-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_app', '0013_service_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='people',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création de la personne'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création du service'),
        ),
    ]
