# Generated by Django 2.0 on 2018-01-18 20:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet_app', '0014_auto_20180118_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
