# Generated by Django 2.0 on 2018-01-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_app', '0015_auto_20180118_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Clinique Vétérinaire', help_text='Le nom de la clinique apparaît dans le titre du site', max_length=300, verbose_name='Nom de la clinique')),
            ],
            options={
                'verbose_name': 'Paramètre de la clinique',
            },
        ),
    ]
