# Generated by Django 2.0 on 2018-01-20 14:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('vet_app', '0016_clinicconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicconfiguration',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Numéro de la clinique'),
        ),
    ]
