# Generated by Django 2.0 on 2018-01-20 15:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('vet_app', '0017_clinicconfiguration_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicconfiguration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de la clinique'),
        ),
        migrations.AlterField(
            model_name='clinicconfiguration',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Numéro de téléphone de la clinique'),
        ),
    ]
