# Generated by Django 2.0 on 2018-01-21 08:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vet_app', '0018_auto_20180120_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicOpeningHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening', models.TimeField(verbose_name='Ouverture')),
                ('closing', models.TimeField(verbose_name='Fermeture')),
                ('days', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], max_length=13, verbose_name='Jours')),
            ],
            options={
                'verbose_name': "Horaîres d'ouverture",
            },
        ),
        migrations.AddField(
            model_name='clinicconfiguration',
            name='opening_hours',
            field=models.ManyToManyField(blank=True, to='vet_app.ClinicOpeningHour', verbose_name="Horaires d'ouverture"),
        ),
    ]
