# Generated by Django 2.0 on 2018-01-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_app', '0020_auto_20180121_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicconfiguration',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Adresse de la clinique'),
        ),
    ]
